### ISSUE TITLE
大佬你好，请问api返回的数据不完全要怎么办

### ISSUE THREAD

**Issue by MK331** [Fog-Forest/Steam-page#4]
这是我的SteamID76561198840919905
返回的数据如图![](https://i.imgur.com/Dr8PufT.png)

**Comment by fog-forest** [comment]
https://api.miao33.top/SteamAPI.php/SteamAPI.php?id=76561198849944519&type=all
没有问题啊~亲
![TIM截图](https://ae01.alicdn.com/kf/H7990f8d96efd4f56a3c7e8254a455859I.jpg)

**Comment by MK331** [comment]
是的，可是这种情况在库里的游戏比较多的情况下会出现，我测试了一些结果，失败的结果如下
[76561198312306320](https://api.miao33.top/SteamAPI.php/SteamAPI.php?id=76561198312306320&type=all)
[76561198356503271](https://api.miao33.top/SteamAPI.php/SteamAPI.php?id=76561198356503271&type=all)

用我的小号以及一些游戏数量在90以下（最高测试结果是85[76561198981882069](https://api.miao33.top/SteamAPI.php/SteamAPI.php?id=76561198981882069&type=all)）的SteamID时可以返回完整的结果

比较明显的反馈图

![](https://i.imgur.com/sIOYTjM.png)

**Comment by fog-forest** [comment]
收到

**Comment by fog-forest** [comment]
已修复
